### ISSUE TITLE
Showing Excerpts in Divi Filterable Portfolios

### ISSUE THREAD

**Issue by bergeson** [kary4/divituts#1]
Hi kary4,
Thank you for your "Moving Filterable Portfolio module to child theme" directions. We use filterable portfolios a lot for staff directories. Can you tell me, once I move the filterable portfolio into the child theme, how I can modify it to always show excerpts? Would love any help you can offer.
Thanks!

**Comment by kary4** [comment]
Hello @bergeson 
Can you please open a ticket in the support forum here 
https://www.elegantthemes.com/forum/viewforum.php?f=187

and let me know? I'll be happy to provide you a solution for this :)
